# PlanHub Pro - Ultra-Compatible Setup Script (v3.1)
# Designed for fresh Windows 10/11 laptops with default PowerShell 5.1

$ErrorActionPreference = "Continue" # Don't stop on minor winget warnings
$LogFile = "$env:TEMP\planhub_setup_log.txt"

function Write-Log($Message, $Color = "White") {
    $TimeStamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "[$TimeStamp] $Message" | Out-File -FilePath $LogFile -Append
    Write-Host "[$TimeStamp] $Message" -ForegroundColor $Color
}

function Write-SimpleFile($Path, $Content) {
    # Use standard UTF8 for maximum compatibility
    [System.IO.File]::WriteAllText($Path, $Content)
}

# --- 0. ADMIN CHECK ---
Write-Log "Checking for Administrator privileges..." "Cyan"
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Log "[ERROR] This script must be run as Administrator." "Red"
    pause
    exit
}

Write-Log "========================================" "Cyan"
Write-Log "   PlanHub Pro - Master Fleet Setup v3.1" "Cyan"
Write-Log "========================================" "Cyan"

# --- 1. USER CONFIGURATION ---
Write-Log "`n[!] LAPTOP CONFIGURATION REQUIRED" "Yellow"
$LaptopID = Read-Host "1. Enter Laptop ID (e.g. Laptop 1)"
$PhEmail = Read-Host "2. Enter PlanHub Email"
$PhPass = Read-Host "3. Enter PlanHub Password"
$State = Read-Host "4. Enter State Code (e.g. TX, CA)"
$Zip = Read-Host "5. Enter Office Zip Code (e.g. 76180)"

if (!$LaptopID -or !$PhEmail) {
    Write-Log "[ERROR] Laptop ID and Email are mandatory." "Red"
    pause
    exit
}

# --- 2. SYSTEM DEPENDENCIES ---
Write-Log "`n[2/8] Installing System Dependencies (Winget)..." "Yellow"

$appIds = @(
    "Git.Git",
    "OpenJS.NodeJS.LTS",
    "Google.Chrome",
    "Python.Python.3.11",
    "UB-Mannheim.TesseractOCR",
    "Microsoft.VCRedist.2015+.x64",
    "PrivateInternetAccess.PrivateInternetAccess"
)

foreach ($id in $appIds) {
    Write-Log "   Checking $id..." "Gray"
    winget install --id $id -e --silent --accept-package-agreements --accept-source-agreements 2>$null
}

# Refresh PATH (Simple version for PS 5.1)
$env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")

# --- 3. WORKSPACE ---
$InstallDir = "C:\planhub"
$ScraperDir = "C:\planhub\planhub-scraper"
$OcrDir = "C:\planhub\ocr-pipeline"

if (!(Test-Path $InstallDir)) { New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null }

# --- 4. CONFIG INJECTION ---
Write-Log "`n[3/8] Injecting Configuration..." "Yellow"

if (!(Test-Path $ScraperDir)) { New-Item -ItemType Directory -Path $ScraperDir -Force | Out-Null }
if (!(Test-Path $OcrDir)) { New-Item -ItemType Directory -Path $OcrDir -Force | Out-Null }

$NL = [Environment]::NewLine
$EnvContent = "# Generated by Setup Script" + $NL
$EnvContent += "PLANHUB_EMAIL=$PhEmail" + $NL
$EnvContent += "PLANHUB_PASSWORD=$PhPass" + $NL
$EnvContent += "LAPTOP_ID=$LaptopID" + $NL
$EnvContent += "PLANHUB_ZIP=$Zip" + $NL
$EnvContent += "STATE=$State" + $NL
$EnvContent += "TELEMETRY_URL=https://planhub-telemetry.itscyper987.workers.dev" + $NL
$EnvContent += "INGEST_TOKEN=a2b5f70d02997a7847dc05bf01b96d0cbc4d957a8f10f616a8c743cba1c7fd26" + $NL
$EnvContent += "PIA_USERNAME=p4414451" + $NL
$EnvContent += "PIA_PASSWORD=D1$p@tch" + $NL

Write-SimpleFile "$ScraperDir\.env" $EnvContent

$OcrConfig = "SHEET_ID = '1mec31wKtllJOS5XdfphXoHO2qV2TC-d9PEQRBPcMdZc'" + $NL
$OcrConfig += "MACHINE_NAME = '$LaptopID'" + $NL
$OcrConfig += "CREDENTIALS_FILE = 'credentials.json'" + $NL
$OcrConfig += "SCREENSHOTS_ROOT = r'../planhub-scraper/screenshots'" + $NL
$OcrConfig += "NUM_WORKERS = 2" + $NL
$OcrConfig += "MIN_CONFIDENCE = 0.6" + $NL
Write-SimpleFile "$OcrDir\config.py" $OcrConfig

# --- 5. INSTALLING CODE ---
Write-Log "`n[4/8] Installing Dependencies..." "Yellow"
Set-Location $ScraperDir
if (Get-Command npm -ErrorAction SilentlyContinue) {
    npm install
    npx playwright install chromium --with-deps
}

# --- 6. OCR ENV ---
Write-Log "`n[5/8] Finalizing OCR..." "Yellow"
Set-Location $OcrDir
if (Get-Command python -ErrorAction SilentlyContinue) {
    python -m venv venv
    .\venv\Scripts\python.exe -m pip install --upgrade pip
    .\venv\Scripts\python.exe -m pip install paddleocr paddlepaddle-gpu>=2.6.2 setuptools opencv-python google-api-python-client google-auth-httplib2 google-auth-oauthlib requests gspread oauth2client
}

Write-Log "`n========================================" "Green"
Write-Log "   INSTALLATION COMPLETE!" "Green"
Write-Log "   Folder: C:\planhub"
Write-Log "========================================" "Green"

pause
