# PlanHub Pro - Ultimate Fleet Setup Script (v2.0)
# This script performs a 100% clean installation for new laptops.

$ErrorActionPreference = "Stop"
$LogFile = "$env:TEMP\planhub_setup_log.txt"

function Write-Log($Message, $Color = "White") {
    $TimeStamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$TimeStamp : $Message" | Out-File -FilePath $LogFile -Append
    Write-Host "[$TimeStamp] $Message" -ForegroundColor $Color
}

# --- 0. ADMIN CHECK ---
Write-Log "Checking for Administrator privileges..." "Cyan"
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Log "[ERROR] This script must be run as Administrator." "Red"
    Write-Log "Please right-click your terminal and 'Run as Administrator'." "Yellow"
    pause
    exit
}

Write-Log "========================================" "Cyan"
Write-Log "   PlanHub Pro - Master Fleet Setup" "Cyan"
Write-Log "========================================" "Cyan"

# --- 1. USER CONFIGURATION ---
Write-Log "`n[!] LAPTOP CONFIGURATION REQUIRED" "Yellow"
$LaptopID = Read-Host "1. Enter Laptop ID (e.g. Laptop 1)"
$PhEmail = Read-Host "2. Enter PlanHub Email"
$PhPass = Read-Host "3. Enter PlanHub Password"
$State = Read-Host "4. Enter State Code (e.g. TX, CA)"
$Zip = Read-Host "5. Enter Office Zip Code (e.g. 76180)"

if ([string]::IsNullOrWhiteSpace($LaptopID) -or [string]::IsNullOrWhiteSpace($PhEmail)) {
    Write-Log "[ERROR] Laptop ID and Email are mandatory." "Red"
    pause
    exit
}

# --- 2. SYSTEM DEPENDENCIES ---
Write-Log "`n[2/7] Installing System Dependencies (Winget)..." "Yellow"

$apps = @(
    @{ id = "Git.Git"; name = "Git" },
    @{ id = "OpenJS.NodeJS.LTS"; name = "Node.js" },
    @{ id = "Google.Chrome"; name = "Google Chrome" },
    @{ id = "Python.Python.3.11"; name = "Python 3.11" },
    @{ id = "UB-Mannheim.TesseractOCR"; name = "Tesseract OCR" },
    @{ id = "PrivateInternetAccess.PrivateInternetAccess"; name = "PIA VPN" }
)

foreach ($app in $apps) {
    if (!(winget list --id $app.id -e 2>$null)) {
        Write-Log "   Installing $($app.name)..." "Gray"
        winget install --id $app.id -e --silent --accept-package-agreements --accept-source-agreements
    } else {
        Write-Log "   $($app.name) already installed." "Green"
    }
}

# Refresh Environment Variables for the current session
Write-Log "   Refreshing PATH environment..." "Gray"
$env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")

# --- 3. WORKSPACE PREPARATION ---
Write-Log "`n[3/7] Preparing Clean Workspace..." "Yellow"
$InstallDir = "C:\planhub"
$OcrDir = "C:\ocr-pipeline"

Write-Host "WARNING: This will COMPLETELY DELETE everything in $InstallDir and $OcrDir." -ForegroundColor "Red"
$ConfirmWipe = Read-Host "Are you sure you want to perform a FACTORY RESET on this laptop? (y/n)"
if ($ConfirmWipe -ne "y") {
    Write-Log "Aborting clean installation as per user request." "Yellow"
    exit
}

# Cleanup existing
foreach ($dir in @($InstallDir, $OcrDir)) {
    if (Test-Path $dir) {
        Write-Log "   Wiping old $dir folder..." "Red"
        # Terminate any running processes that might lock files
        taskkill /F /IM node.exe /T 2>$null
        taskkill /F /IM python.exe /T 2>$null
        Remove-Item $dir -Recurse -Force -ErrorAction SilentlyContinue
    }
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
}

# --- 4. CODE DOWNLOAD ---
Write-Log "`n[4/7] Downloading Latest Automation Fleet..." "Yellow"
Set-Location $InstallDir
git clone https://github.com/faizigfx9934/Plan_Hub_Automation.git .
if ($LASTEXITCODE -ne 0) {
    Write-Log "[ERROR] Git clone failed. Check your internet or GitHub access." "Red"
    pause
    exit
}

# Move OCR to its separate folder as per project architecture
Write-Log "   Splitting OCR components to $OcrDir..." "Gray"
Move-Item -Path "$InstallDir\ocr-pipeline\*" -Destination $OcrDir -Force

# --- 5. CREDENTIALS & CONFIG INJECTION ---
Write-Log "`n[5/7] Injecting Configuration..." "Yellow"

# Scraper .env
$EnvContent = @"
# Generated by Setup Script $(Get-Date)
PLANHUB_EMAIL=$PhEmail
PLANHUB_PASSWORD=$PhPass
LAPTOP_ID=$LaptopID
PLANHUB_ZIP=$Zip
STATE=$State
START_DATE_OFFSET=4
TELEMETRY_URL=https://planhub-telemetry.itscyper987.workers.dev
INGEST_TOKEN=a2b5f70d02997a7847dc05bf01b96d0cbc4d957a8f10f616a8c743cba1c7fd26
PIA_USERNAME=p4414451
PIA_PASSWORD=D1$`p@tch
"@
$EnvContent | Out-File -FilePath "$InstallDir\.env" -Encoding utf8

# OCR config.py (Linked to scraper screenshots)
$OcrConfig = @"
SHEET_ID = "1mec31wKtllJOS5XdfphXoHO2qV2TC-d9PEQRBPcMdZc"
MACHINE_NAME = "$LaptopID"
CREDENTIALS_FILE = "credentials.json"
SCREENSHOTS_ROOT = r"C:\planhub\screenshots"
DISCORD_WEBHOOK_URLS = [
    "https://discord.com/api/webhooks/1496914813735927950/gTWQFxHkWuABBkRu0vbpWJq2FWdhjH8n3JloB9AhmpO-RUhE91EOrdjp8kPkRAh4IHS2",
]
NUM_WORKERS = 2
MIN_CONFIDENCE = 0.6
"@
$OcrConfig | Out-File -FilePath "$OcrDir\config.py" -Encoding utf8

# OCR Google Credentials (Base64)
$B64Creds = 'ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAicGxhbmh1Yi1kYXRhIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiNTVjMDM2MzMzOWY5MDYyNDExM2M0ZmEzY2I2MDI3ODQ4MmJiMjBiNyIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZBSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS1l3Z2dTaUFnRUFBb0lCQVFDdVpyN1VzRDhJOW1XaFxuanNXOWZyc3I2Q1gxcFhKOE1BTFh0dUEveThXNFc1a2tGUGhUSWRjQzhUNWtQUi9ONmt0bHBISE5CYmxSUlNZbVxuYWRacFBzTHpCVE1GZEZDRVZuUjNvWWl4RmFTc3labHl1VjJPbTFZTm5IU1YwRytBb2hlNWxINmVzMk5JcnErOVxuMnNmWC9ra3l3ZkxXMG1yRURJN3AxeUczVkN5L2RXclFEVGFnR3RTZ2cxVDJKd3p4RVNSWkdPKzBVb2RjbFBFaFxuZk9qUWFCZmFRM1JYcmFNakFDWEFEdG1qL1VWaDgyRDkvb0J1R3ZMamIxbVV5aXQvRVdPSnBxL3JBdWdFL1BKMlxubmlacDV3R1hDU2VpQmJBZFAyL2N5VWdCQnozbHRxcC9sRExtMkU0OUxkaGNnVVpqY3RVOXBQYjJFZnJMaWUxb1xuK2htK080akRBZ01CQUFFQ2dnRUFCVlMzRkMrSHlYZmhVYTBjc0VHeFlZR1oreXpkYlBHMUo3eVpZYzhyNVU2TlxuVnZMeHJpRFp6NXA2L2RFQXcyaGdlWDNGSVVqajF1OGV4bW4wRHlMWVVvejVpUU42MkMrcWVzbXAvYWFzMks2NlxuTi9wQ3NGQ0RYVmVMMURybjl6clNoVjFicFBGTUE0OFQ4UlJSNzZSM3ZwZ3VLNkh2RWF0M1JMeFRsN1lBeDF4UlxuYURLWGhkVUJEWm5RMTRTYk5TZE4xeUpObUxNcnp2dllzVVIvL2R1THAvd1pBRW9IVlI1eUZjRU5OYmt0WFhMb1xuNEVGYlNkbkVxeVAyZlcyUG5QcUxFZ3dvTXcxV2VWaWU2ZlhWZU1LbVl1RDJnNmpTZVJMdGZkZmJ0TCt6empvNlxuQUZKNHNoT2pTbUhYVVd0OVRhaUZHSDNEYVQ1OHlMTzkxU2hiWm4wdFdRS0JnUURXNGlLWUFHOXUyTjJmaWt4R1xuS2tFb2xtMDJUcVRFODV4TDJ2MURlK1BwTlJiZTA3aVZ1MGlrZTNOcDdvUjZTQkRKcy9ZbGVTWmNmS0ZpanExRFxuWm10NFZ5ZXMweWJBeHJTdXJMTjluSnlYV3ZzL0Q1OTlnQWZzUUNtb2pTT1ZBMTlDZ0crSExGc00yZ2ExdXRUSFxuVEMrSElPK0hVT1RmY1o2bHRKZTFZaWtEVFFLQmdRRFB4YU1HS21pNDVRbjhQQkpReDM4clJMT056WTAzNm1aWFxuSlhHNTNndDVHdllFMjMrOHVYUjA1ZGhqamd1dXNheXdqL0JXZFNwWXl0TzRYVjd0Um5pYkx4NXlicXdmS2lma1xuVUdUUXN2ZVlsTEEyZXFXTVdHd214NGlpckJDMUsycTVmLzE2cmljMGVDVWFkazhibmNYbGl4cTEzSDlLUXJBSFxuQVFhKzJOZVVUd0tCZ0hwcndOdXFPOUlCK1ZsQU9DNHRPb3YrRDJCR003Y0ZOd0U4Vk5lU2lJaS9OelZobDZLdVxuWFRkZ0lhT3pRSVJOOUVxRm5YRkI4U24xMHhmTVEwZkgzT2hsZHZRT0krRG1FK0FFQWdwSkpDbFNxeHNGTW84VVxuVnU4d3Fzc2RCYTJLaTBYZTJDdEJpT25zZUxBbUxiMFJXVzU1eEJ6cWFFb29lQUxkdlNTWU5OZHRBb0dBRTQrTlxueTVUT2l5bTFDUFEyM1RnSzl1M2U0YWpLZE1zeW0xM0JHVGlZWit4cjRRVXhQM2xPUjNza0ppdEhXa2tMOHd0NlxuR3dtbzFQY3plNVgreStQb2t1T2F3RGMvS1NmMDNYL2NIZkhiY1pmK0J3TUE5dmVVSndwK0NLS2VhQkFRV2lwOFxubU1Jd21yWDgrRUxQSzlCc3d6R1hjQ3UwS0MrakZ1VzMxdHZmWCswQ2dZQlcwYnBSaG10TG1VZE9tUkpFMCt5S1xuTTFFaXBLTWdxYkJmVWVpSHdDVElBVE05a2pnRVFzTkEvS0hSeXdrYmFtU2FYYnBTMWRXSVduWFY3M1V0MXM3SVxubE9lRUdnblJFN1NsSVJMQ25XRitBaVNxWjlzVDlHYzk1WGFSTXZEU3ZEalNPbzYzamxwMFBHdTVhbzFGSHhhWVxuWnpPOXFuVFVDZGNKcm9SbStUUnNDdz09XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAicGxhbmh1Yi1kYXRhQHBsYW5odWItZGF0YS5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMDA3MjYwMzEyMDM3NTUzMzc4MzQiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L3BsYW5odWItZGF0YSU0MHBsYW5odWItZGF0YS5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgInVuaXZlcnNlX2RvbWFpbiI6ICJnb29nbGVhcGlzLmNvbSIKfQo='
$CredsJson = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($B64Creds))
$CredsJson | Out-File -FilePath "$OcrDir\credentials.json" -Encoding utf8

# --- 6. SCRAPER DEPENDENCIES ---
Write-Log "`n[6/7] Finalizing Scraper Environment..." "Yellow"
Set-Location $InstallDir
# Check if npm is available
if (Get-Command npm -ErrorAction SilentlyContinue) {
    Write-Log "   Running npm install..." "Gray"
    npm install
    Write-Log "   Installing Playwright Browsers & Dependencies..." "Gray"
    npx playwright install chromium --with-deps
} else {
    Write-Log "[WARNING] npm not found in current session. You may need to run 'npm install' manually after restart." "Yellow"
}

# --- 7. OCR DEPENDENCIES ---
Write-Log "`n[7/7] Finalizing OCR Environment (Python venv)..." "Yellow"
Set-Location $OcrDir
# Check if python is available
if (Get-Command python -ErrorAction SilentlyContinue) {
    Write-Log "   Creating virtual environment..." "Gray"
    python -m venv venv
    Write-Log "   Installing OCR requirements (PaddleOCR, etc)..." "Gray"
    venv\Scripts\python.exe -m pip install --upgrade pip
    venv\Scripts\python.exe -m pip install -r requirements.txt --no-cache-dir
    Write-Log "   Verifying Google API access..." "Gray"
    venv\Scripts\python.exe -c "import google.oauth2; import gspread; print('SUCCESS')"
} else {
    Write-Log "[WARNING] python not found in current session. You may need to run 'SETUP-OCR.bat' manually." "Yellow"
}

Write-Log "`n========================================" "Green"
Write-Log "   CLEAN INSTALLATION COMPLETE!" "Green"
Write-Log "   Log saved to: $LogFile"
Write-Log "========================================" "Green"
Write-Log "`nNEXT STEPS:"
Write-Log "1. Open 'C:\planhub' and run 'run-control-center.bat'."
Write-Log "2. Open 'C:\ocr-pipeline' and run 'RUN.bat'."
Write-Log "3. Ensure PIA VPN is logged in and active."

pause
